################
# mapMetasToRefs.sub
# Submission script for mapping metagenomic reads to a ref genome or assembly
# Elizabeth McDaniel


request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/obscurePOS/executables/mapMetasToRefs.sh
arguments = $(ref) $(meta) $(out)

output = /home/GLBRCORG/emcdaniel/obscurePOS/outs/$(Cluster)_$(Process)_mapping.out
error = /home/GLBRCORG/emcdaniel/obscurePOS/errs/$(Cluster)_$(Process)_mapping.err
log = /home/GLBRCORG/emcdaniel/obscurePOS/logs/$(Cluster)_$(Process)_mapping.log

queue ref,meta,out from /home/GLBRCORG/emcdaniel/obscurePOS/metadata/obscurePOS-mappingCombos.txt
