##################
# fastp_filter.sub
# Submission script for reformatting metagenomic reads
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/obscurePOS/executables/reformat-reads.sh
arguments = $(r1) $(r2) $(out)

output = /home/GLBRCORG/emcdaniel/obscurePOS/outs/$(Cluster)_$(Process)_reformat.out
error = /home/GLBRCORG/emcdaniel/obscurePOS/errs/$(Cluster)_$(Process)_reformat.err
log = /home/GLBRCORG/emcdaniel/obscurePOS/logs/$(Cluster)_$(Process)_reformat.log

queue r1,r2,out from metadata/POS-reformatting-queue.txt
