######################
# Queue single assemblies with SPAdes on WEI GLBRC
# Elizabeth McDaniel
######################

request_cpus = 24
request_memory = 600GB

executable = /home/GLBRCORG/emcdaniel/obscurePOS/executables/single_assembly.sh
arguments = $(output) $(r1) $(r2)

output = /home/GLBRCORG/emcdaniel/obscurePOS/outs/$(sample)_assemble.out
error = /home/GLBRCORG/emcdaniel/obscurePOS/errs/$(sample)_assemble.err
log = /home/GLBRCORG/emcdaniel/obscurePOS/logs/$(sample)_assemble.log

queue output,r1,r2 from metadata/POS-2015-08-06-redo-assembly.txt
